[2024-05-20T03:13:18.772+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T03:13:18.792+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL.transformar_data scheduled__2024-05-20T02:00:00+00:00 [queued]>
[2024-05-20T03:13:18.799+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL.transformar_data scheduled__2024-05-20T02:00:00+00:00 [queued]>
[2024-05-20T03:13:18.799+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-20T03:13:18.810+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar_data> on 2024-05-20 02:00:00+00:00
[2024-05-20T03:13:18.816+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=63) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-20T03:13:18.817+0000] {standard_task_runner.py:63} INFO - Started process 65 to run task
[2024-05-20T03:13:18.817+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL', 'transformar_data', 'scheduled__2024-05-20T02:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpy853v4rs']
[2024-05-20T03:13:18.819+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask transformar_data
[2024-05-20T03:13:18.855+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL.transformar_data scheduled__2024-05-20T02:00:00+00:00 [running]> on host c86991a6c271
[2024-05-20T03:13:18.925+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ETL' AIRFLOW_CTX_TASK_ID='transformar_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-20T02:00:00+00:00'
[2024-05-20T03:13:18.927+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T03:13:19.522+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T03:13:19.523+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_connect.py", line 33, in extract_transform
    stock['sector'] = '' if stock['sector'] is None else stock['sector']
                            ~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-05-20T03:13:19.530+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_ETL, task_id=transformar_data, run_id=scheduled__2024-05-20T02:00:00+00:00, execution_date=20240520T020000, start_date=20240520T031318, end_date=20240520T031319
[2024-05-20T03:13:19.539+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 26 for task transformar_data (string indices must be integers, not 'str'; 65)
[2024-05-20T03:13:19.552+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-20T03:13:19.569+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-20T03:13:19.572+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-20T03:59:43.672+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T03:59:43.701+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL.transformar_data scheduled__2024-05-20T02:00:00+00:00 [queued]>
[2024-05-20T03:59:43.711+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL.transformar_data scheduled__2024-05-20T02:00:00+00:00 [queued]>
[2024-05-20T03:59:43.712+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-20T03:59:43.735+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar_data> on 2024-05-20 02:00:00+00:00
[2024-05-20T03:59:43.742+0000] {standard_task_runner.py:63} INFO - Started process 78 to run task
[2024-05-20T03:59:43.745+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL', 'transformar_data', 'scheduled__2024-05-20T02:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpmp2c8y74']
[2024-05-20T03:59:43.748+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask transformar_data
[2024-05-20T03:59:43.791+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL.transformar_data scheduled__2024-05-20T02:00:00+00:00 [running]> on host a5a7be3e911e
[2024-05-20T03:59:43.856+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ETL' AIRFLOW_CTX_TASK_ID='transformar_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-20T02:00:00+00:00'
[2024-05-20T03:59:43.858+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T03:59:44.521+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T03:59:44.521+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/api_connect.py", line 33, in extract_transform
    stock['sector'] = '' if stock['sector'] is None else stock['sector']
TypeError: string indices must be integers
[2024-05-20T03:59:44.530+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_ETL, task_id=transformar_data, run_id=scheduled__2024-05-20T02:00:00+00:00, execution_date=20240520T020000, start_date=20240520T035943, end_date=20240520T035944
[2024-05-20T03:59:44.540+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task transformar_data (string indices must be integers; 78)
[2024-05-20T03:59:44.559+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-20T03:59:44.577+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-20T03:59:44.580+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
