[2024-05-21T02:26:44.977+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T02:26:44.995+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL.conexion_load_redshift manual__2024-05-21T02:26:40.683783+00:00 [queued]>
[2024-05-21T02:26:45.002+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL.conexion_load_redshift manual__2024-05-21T02:26:40.683783+00:00 [queued]>
[2024-05-21T02:26:45.002+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-21T02:26:45.013+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): conexion_load_redshift> on 2024-05-21 02:26:40.683783+00:00
[2024-05-21T02:26:45.018+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=450) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T02:26:45.019+0000] {standard_task_runner.py:63} INFO - Started process 451 to run task
[2024-05-21T02:26:45.019+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL', 'conexion_load_redshift', 'manual__2024-05-21T02:26:40.683783+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpmyv6xs3p']
[2024-05-21T02:26:45.019+0000] {standard_task_runner.py:91} INFO - Job 91: Subtask conexion_load_redshift
[2024-05-21T02:26:45.048+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL.conexion_load_redshift manual__2024-05-21T02:26:40.683783+00:00 [running]> on host 22cda28e7059
[2024-05-21T02:26:45.117+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ETL' AIRFLOW_CTX_TASK_ID='conexion_load_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T02:26:40.683783+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T02:26:40.683783+00:00'
[2024-05-21T02:26:45.118+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T02:26:46.515+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T02:26:46.515+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_connect.py", line 172, in connect_load
    cursor.execute("""
psycopg2.errors.InvalidTableDefinition: multiple primary keys for table "stocks_prices" are not allowed

[2024-05-21T02:26:46.522+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_ETL, task_id=conexion_load_redshift, run_id=manual__2024-05-21T02:26:40.683783+00:00, execution_date=20240521T022640, start_date=20240521T022644, end_date=20240521T022646
[2024-05-21T02:26:46.532+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 91 for task conexion_load_redshift (multiple primary keys for table "stocks_prices" are not allowed
; 451)
[2024-05-21T02:26:46.556+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-21T02:26:46.567+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T02:26:46.568+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
