[2024-05-21T02:07:15.504+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T02:07:15.520+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL.conexion_redshift manual__2024-05-21T02:07:11.497045+00:00 [queued]>
[2024-05-21T02:07:15.528+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL.conexion_redshift manual__2024-05-21T02:07:11.497045+00:00 [queued]>
[2024-05-21T02:07:15.528+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-21T02:07:15.540+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): conexion_redshift> on 2024-05-21 02:07:11.497045+00:00
[2024-05-21T02:07:15.545+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=184) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T02:07:15.545+0000] {standard_task_runner.py:63} INFO - Started process 185 to run task
[2024-05-21T02:07:15.546+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL', 'conexion_redshift', 'manual__2024-05-21T02:07:11.497045+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmprqzz7opf']
[2024-05-21T02:07:15.546+0000] {standard_task_runner.py:91} INFO - Job 88: Subtask conexion_redshift
[2024-05-21T02:07:15.576+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL.conexion_redshift manual__2024-05-21T02:07:11.497045+00:00 [running]> on host 22cda28e7059
[2024-05-21T02:07:15.640+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ETL' AIRFLOW_CTX_TASK_ID='conexion_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T02:07:11.497045+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T02:07:11.497045+00:00'
[2024-05-21T02:07:15.641+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T02:07:16.447+0000] {xcom.py:675} ERROR - Object of type connection is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-05-21T02:07:16.449+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T02:07:16.450+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'psycopg2.extensions.connection'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_connect.py", line 65, in connect_redshift
    ti.xcom_push(key="conn", value=conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type connection is not JSON serializable
[2024-05-21T02:07:16.457+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_ETL, task_id=conexion_redshift, run_id=manual__2024-05-21T02:07:11.497045+00:00, execution_date=20240521T020711, start_date=20240521T020715, end_date=20240521T020716
[2024-05-21T02:07:16.467+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 88 for task conexion_redshift (Object of type connection is not JSON serializable; 185)
[2024-05-21T02:07:16.481+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-21T02:07:16.497+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T02:07:16.500+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
