[2024-05-20T02:41:46.337+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T02:41:46.354+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL.transformar_data manual__2024-05-20T02:09:40.662398+00:00 [queued]>
[2024-05-20T02:41:46.360+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL.transformar_data manual__2024-05-20T02:09:40.662398+00:00 [queued]>
[2024-05-20T02:41:46.360+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-20T02:41:46.370+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformar_data> on 2024-05-20 02:09:40.662398+00:00
[2024-05-20T02:41:46.377+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=73) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-20T02:41:46.378+0000] {standard_task_runner.py:63} INFO - Started process 75 to run task
[2024-05-20T02:41:46.378+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL', 'transformar_data', 'manual__2024-05-20T02:09:40.662398+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpks11hsfi']
[2024-05-20T02:41:46.380+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask transformar_data
[2024-05-20T02:41:46.418+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL.transformar_data manual__2024-05-20T02:09:40.662398+00:00 [running]> on host c86991a6c271
[2024-05-20T02:41:46.479+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ETL' AIRFLOW_CTX_TASK_ID='transformar_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T02:09:40.662398+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-20T02:09:40.662398+00:00'
[2024-05-20T02:41:46.480+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T02:41:46.989+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T02:41:46.990+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_connect.py", line 34, in extract_transform
    stock['sector'] = '' if stock['sector'] is None else stock['sector']
                            ~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2024-05-20T02:41:46.997+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_ETL, task_id=transformar_data, run_id=manual__2024-05-20T02:09:40.662398+00:00, execution_date=20240520T020940, start_date=20240520T024146, end_date=20240520T024146
[2024-05-20T02:41:47.007+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task transformar_data (string indices must be integers, not 'str'; 75)
[2024-05-20T02:41:47.032+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-20T02:41:47.049+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-20T02:41:47.052+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
