[2024-05-21T03:03:16.506+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T03:03:16.534+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ETL.conexion_load_redshift manual__2024-05-21T03:03:12.005150+00:00 [queued]>
[2024-05-21T03:03:16.543+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ETL.conexion_load_redshift manual__2024-05-21T03:03:12.005150+00:00 [queued]>
[2024-05-21T03:03:16.543+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-21T03:03:16.556+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): conexion_load_redshift> on 2024-05-21 03:03:12.005150+00:00
[2024-05-21T03:03:16.561+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=312) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T03:03:16.561+0000] {standard_task_runner.py:63} INFO - Started process 313 to run task
[2024-05-21T03:03:16.562+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ETL', 'conexion_load_redshift', 'manual__2024-05-21T03:03:12.005150+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpaye2e76u']
[2024-05-21T03:03:16.563+0000] {standard_task_runner.py:91} INFO - Job 108: Subtask conexion_load_redshift
[2024-05-21T03:03:16.593+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ETL.conexion_load_redshift manual__2024-05-21T03:03:12.005150+00:00 [running]> on host 22cda28e7059
[2024-05-21T03:03:16.662+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ETL' AIRFLOW_CTX_TASK_ID='conexion_load_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T03:03:12.005150+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T03:03:12.005150+00:00'
[2024-05-21T03:03:16.663+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T03:08:51.250+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-21T03:08:51.251+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T03:08:51.260+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_ETL, task_id=conexion_load_redshift, run_id=manual__2024-05-21T03:03:12.005150+00:00, execution_date=20240521T030312, start_date=20240521T030316, end_date=20240521T030851
[2024-05-21T03:08:51.285+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-21T03:08:51.298+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T03:08:51.300+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
